### ISSUE TITLE
Is grafana dashboard available?

### ISSUE THREAD

**Issue by sl0n** [eko/tado-exporter#19]
Hello,

First of all thank you for this project!

I wonder if you can publish relevant grafana's dashboard code as well?

Cheers!

**Comment by caraar12345** [comment]
Hi! I just published the Grafana dashboard that I use with this. 

https://grafana.com/grafana/dashboards/13623

**Comment by eko** [comment]
Nice one, thank you @caraar12345 👍

Could you please submit a PR on this repository to specify the Grafana dashboard into the README file when you will have some time?

I close this issue for now, feel free to reopen if needed.

Thanks
